# ---- Constantes -------------------------------------------

CASH_TOPIC = "cajero/efectivo"
MIN_TOPIC = "cajero/limite_min"
MAX_TOPIC = "cajero/limite_max"
PIN_REQUEST_TOPIC = "cajero/pin_request"
PIN_RESPONSE_TOPIC = "cajero/pin_response"
STATUS_TOPIC = "cajero/status"
MONTO_REQUEST_TOPIC = "cajero/monto_request"
MONTO_RESPONSE_TOPIC = "cajero/monto_response"
INGRESO_REQUEST_TOPIC = "cajero/ingreso_request"
INGRESO_RESPONSE_TOPIC = "cajero/ingreso_response"
RETIRO_REQUEST_TOPIC = "cajero/retiro_request"
RETIRO_RESPONSE_TOPIC = "cajero/retiro_response"
CBU_REQUEST_TOPIC = "cajero/cbu_request"
CBU_RESPONSE_TOPIC = "cajero/cbu_response"